ALTER TABLE users ADD COLUMN IF NOT EXISTS bio                VARCHAR(300);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "profileImageUrl"  VARCHAR(400);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "websiteUrl"       VARCHAR(200);
